pipeline:
  deploy:
    image: nytimes/drone-gae:latest
    action: deploy
    project: colinjhiggins
    version: "${DRONE_COMMIT}"
    max_versions: 4
    secrets:
      - source: google_credentials
        target: GAE_CREDENTIALS
    when:
      branch: [master]
      event: push
